// Code generated by "genprotocol -ver=ac2fd1af64d4f1613e3d88467403507d7d0ff89c9b04f7811f8dd396f85bb42f -basedir=. -prefix=w3d -statstype=int"

package w3d_obj

type ReqInvalid_data struct {
	Dummy uint8
}
type RspInvalid_data struct {
	Dummy uint8
}

type ReqMakeTeam_data struct {
	Dummy uint8
}
type RspMakeTeam_data struct {
	Dummy uint8
}

type ReqAct_data struct {
	Dummy uint8
}
type RspAct_data struct {
	Dummy uint8
}

type ReqHeartbeat_data struct {
	Tick int64
}
type RspHeartbeat_data struct {
	Tick int64
}

type ReqNearInfo_data struct {
	Dummy uint8
}
type RspNearInfo_data struct {
	Dummy uint8
}

type ReqWorldInfo_data struct {
	Dummy uint8
}
type RspWorldInfo_data struct {
	Dummy uint8
}

type NotiInvalid_data struct {
	Dummy uint8
}

type NotiStatsInfo_data struct {
	Dummy uint8
}
