// Code generated by "genprotocol -ver=fd815e2fbc449528b4fb5d55480af0a03b4bfaf074ff2c5570d2e5a3ce03896b -basedir=. -prefix=w3d -statstype=int"

package w3d_obj

/* protocol template

type ReqInvalid_data struct {
	Dummy uint8
}
type RspInvalid_data struct {
	Dummy uint8
}

type ReqLogin_data struct {
	Dummy uint8
}
type RspLogin_data struct {
	Dummy uint8
}

type ReqHeartbeat_data struct {
	Dummy uint8
}
type RspHeartbeat_data struct {
	Dummy uint8
}

type ReqChat_data struct {
	Dummy uint8
}
type RspChat_data struct {
	Dummy uint8
}

type ReqEnterStage_data struct {
	Dummy uint8
}
type RspEnterStage_data struct {
	Dummy uint8
}

type NotiInvalid_data struct {
	Dummy uint8
}

type NotiStageInfo_data struct {
	Dummy uint8
}

type NotiStatsInfo_data struct {
	Dummy uint8
}

type NotiStageChat_data struct {
	Dummy uint8
}

*/
