// Code generated by "genprotocol -ver=de39b3963afaad4ed2557809c9208a5676bf9321c0823e0dac15bc4db6d51552 -basedir=. -prefix=w3d -statstype=int"

package w3d_handlenoti

/* bytes base demux fn map template

var DemuxNoti2ByteFnMap = [...]func(me interface{}, hd w3d_packet.Header, rbody []byte) error {
w3d_idnoti.Invalid : bytesRecvNotiFn_Invalid,
w3d_idnoti.StageInfo : bytesRecvNotiFn_StageInfo,
w3d_idnoti.StatsInfo : bytesRecvNotiFn_StatsInfo,
w3d_idnoti.StageChat : bytesRecvNotiFn_StageChat,

}

	func bytesRecvNotiFn_Invalid(me interface{}, hd w3d_packet.Header, rbody []byte) error {
		robj, err := w3d_json.UnmarshalPacket(hd, rbody)
		if err != nil {
			return fmt.Errorf("Packet type miss match %v", rbody)
		}
		recved , ok := robj.(*w3d_obj.NotiInvalid_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", robj )
		}
		return fmt.Errorf("Not implemented %v", recved)
	}

	func bytesRecvNotiFn_StageInfo(me interface{}, hd w3d_packet.Header, rbody []byte) error {
		robj, err := w3d_json.UnmarshalPacket(hd, rbody)
		if err != nil {
			return fmt.Errorf("Packet type miss match %v", rbody)
		}
		recved , ok := robj.(*w3d_obj.NotiStageInfo_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", robj )
		}
		return fmt.Errorf("Not implemented %v", recved)
	}

	func bytesRecvNotiFn_StatsInfo(me interface{}, hd w3d_packet.Header, rbody []byte) error {
		robj, err := w3d_json.UnmarshalPacket(hd, rbody)
		if err != nil {
			return fmt.Errorf("Packet type miss match %v", rbody)
		}
		recved , ok := robj.(*w3d_obj.NotiStatsInfo_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", robj )
		}
		return fmt.Errorf("Not implemented %v", recved)
	}

	func bytesRecvNotiFn_StageChat(me interface{}, hd w3d_packet.Header, rbody []byte) error {
		robj, err := w3d_json.UnmarshalPacket(hd, rbody)
		if err != nil {
			return fmt.Errorf("Packet type miss match %v", rbody)
		}
		recved , ok := robj.(*w3d_obj.NotiStageChat_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", robj )
		}
		return fmt.Errorf("Not implemented %v", recved)
	}

*/
