// Code generated by "genprotocol -ver=56f7fdcb1d3890519b70a4ebb8c1f4f8c38a8b3f846e651266e96ce857513f5c -basedir=. -prefix=w3d -statstype=int"

package w3d_handlenoti

/* obj base demux fn map template

var DemuxNoti2ObjFnMap = [...]func(me interface{}, hd w3d_packet.Header, body interface{}) error {
w3d_idnoti.Invalid : objRecvNotiFn_Invalid, // Invalid not used, make empty packet error
w3d_idnoti.StageInfo : objRecvNotiFn_StageInfo, // StageInfo for client display
w3d_idnoti.StatsInfo : objRecvNotiFn_StatsInfo, // StatsInfo game stats info
w3d_idnoti.StageChat : objRecvNotiFn_StageChat, // StageChat broadcasted chat

}

	// Invalid not used, make empty packet error
	func objRecvNotiFn_Invalid(me interface{}, hd w3d_packet.Header, body interface{}) error {
		robj , ok := body.(*w3d_obj.NotiInvalid_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	// StageInfo for client display
	func objRecvNotiFn_StageInfo(me interface{}, hd w3d_packet.Header, body interface{}) error {
		robj , ok := body.(*w3d_obj.NotiStageInfo_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	// StatsInfo game stats info
	func objRecvNotiFn_StatsInfo(me interface{}, hd w3d_packet.Header, body interface{}) error {
		robj , ok := body.(*w3d_obj.NotiStatsInfo_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	// StageChat broadcasted chat
	func objRecvNotiFn_StageChat(me interface{}, hd w3d_packet.Header, body interface{}) error {
		robj , ok := body.(*w3d_obj.NotiStageChat_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

*/
