// Code generated by "genprotocol -ver=f5b1d289172cf84ad5d01b91533408be6b17961cf28ddd6fe767224298a8aedd -basedir=. -prefix=w3d -statstype=int"

package w3d_handlenoti

/* obj base demux fn map template

var DemuxNoti2ObjFnMap = [...]func(me interface{}, hd w3d_packet.Header, body interface{}) error {
w3d_idnoti.Invalid : objRecvNotiFn_Invalid,
w3d_idnoti.StageInfo : objRecvNotiFn_StageInfo,
w3d_idnoti.StatsInfo : objRecvNotiFn_StatsInfo,

}

	func objRecvNotiFn_Invalid(me interface{}, hd w3d_packet.Header, body interface{}) error {
		robj , ok := body.(*w3d_obj.NotiInvalid_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	func objRecvNotiFn_StageInfo(me interface{}, hd w3d_packet.Header, body interface{}) error {
		robj , ok := body.(*w3d_obj.NotiStageInfo_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	func objRecvNotiFn_StatsInfo(me interface{}, hd w3d_packet.Header, body interface{}) error {
		robj , ok := body.(*w3d_obj.NotiStatsInfo_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

*/
