// Code generated by "genprotocol.exe -ver=69ee1a9a014411856ae5de810035b3c3478b3ee188bf040ff46c3ec85f20aba5 -basedir=protocol_w3d -prefix=w3d -statstype=int"

package w3d_handlenoti

import (
	"fmt"

	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_idnoti"
	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_obj"
	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_packet"
)

// obj base demux fn map

var DemuxNoti2ObjFnMap = [...]func(me interface{}, hd w3d_packet.Header, body interface{}) error{
	w3d_idnoti.Invalid:   objRecvNotiFn_Invalid,   // Invalid not used, make empty packet error
	w3d_idnoti.StageInfo: objRecvNotiFn_StageInfo, // StageInfo for client display
	w3d_idnoti.StageChat: objRecvNotiFn_StageChat, // StageChat broadcasted chat

}

// Invalid not used, make empty packet error
func objRecvNotiFn_Invalid(me interface{}, hd w3d_packet.Header, body interface{}) error {
	robj, ok := body.(*w3d_obj.NotiInvalid_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", body)
	}
	return fmt.Errorf("Not implemented %v", robj)
}

// StageInfo for client display
func objRecvNotiFn_StageInfo(me interface{}, hd w3d_packet.Header, body interface{}) error {
	robj, ok := body.(*w3d_obj.NotiStageInfo_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", body)
	}
	return fmt.Errorf("Not implemented %v", robj)
}

// StageChat broadcasted chat
func objRecvNotiFn_StageChat(me interface{}, hd w3d_packet.Header, body interface{}) error {
	robj, ok := body.(*w3d_obj.NotiStageChat_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", body)
	}
	return fmt.Errorf("Not implemented %v", robj)
}
