// Code generated by "genprotocol -ver=69ee1a9a014411856ae5de810035b3c3478b3ee188bf040ff46c3ec85f20aba5 -basedir=. -prefix=w3d -statstype=int"

package w3d_idnoti

import "fmt"

type NotiID uint16 // use in packet header, DO NOT CHANGE
const (
	Invalid   NotiID = iota // not used, make empty packet error
	StageInfo               // for client display
	StageChat               // broadcasted chat

	NotiID_Count int = iota
)

var _NotiID2string = [NotiID_Count][2]string{
	Invalid:   {"Invalid", "not used, make empty packet error"},
	StageInfo: {"StageInfo", "for client display"},
	StageChat: {"StageChat", "broadcasted chat"},
}

func (e NotiID) String() string {
	if e >= 0 && e < NotiID(NotiID_Count) {
		return _NotiID2string[e][0]
	}
	return fmt.Sprintf("NotiID%d", uint16(e))
}
func (e NotiID) CommentString() string {
	if e >= 0 && e < NotiID(NotiID_Count) {
		return _NotiID2string[e][1]
	}
	return ""
}

var _string2NotiID = map[string]NotiID{
	"Invalid":   Invalid,
	"StageInfo": StageInfo,
	"StageChat": StageChat,
}

func String2NotiID(s string) (NotiID, bool) {
	v, b := _string2NotiID[s]
	return v, b
}
