// Code generated by "genprotocol -ver=f5b1d289172cf84ad5d01b91533408be6b17961cf28ddd6fe767224298a8aedd -basedir=. -prefix=w3d -statstype=int"

package w3d_idnoti

import "fmt"

type NotiID uint16 // use in packet header, DO NOT CHANGE
const (
	Invalid   NotiID = iota //
	StageInfo               //
	StatsInfo               // // game stats info

	NotiID_Count int = iota
)

var _NotiID2string = [NotiID_Count]string{
	Invalid:   "Invalid",
	StageInfo: "StageInfo",
	StatsInfo: "StatsInfo",
}

func (e NotiID) String() string {
	if e >= 0 && e < NotiID(NotiID_Count) {
		return _NotiID2string[e]
	}
	return fmt.Sprintf("NotiID%d", uint16(e))
}

var _string2NotiID = map[string]NotiID{
	"Invalid":   Invalid,
	"StageInfo": StageInfo,
	"StatsInfo": StatsInfo,
}

func String2NotiID(s string) (NotiID, bool) {
	v, b := _string2NotiID[s]
	return v, b
}
