// Code generated by "genprotocol -ver=69ee1a9a014411856ae5de810035b3c3478b3ee188bf040ff46c3ec85f20aba5 -basedir=. -prefix=w3d -statstype=int"

package w3d_version

const ProtocolVersion = "69ee1a9a014411856ae5de810035b3c3478b3ee188bf040ff46c3ec85f20aba5"
