// Code generated by "genprotocol -ver=a99e26984c4d0465e81623a4767d3a2aa3cb4fcc9890904054c0c51f30e0b79f -basedir=protocol_w3d -prefix=w3d -statstype=int"

package w3d_version

const ProtocolVersion = "a99e26984c4d0465e81623a4767d3a2aa3cb4fcc9890904054c0c51f30e0b79f"
