// Code generated by "genprotocol.exe -ver=69ee1a9a014411856ae5de810035b3c3478b3ee188bf040ff46c3ec85f20aba5 -basedir=protocol_w3d -prefix=w3d -statstype=int"

package w3d_handlersp

import (
	"fmt"

	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_idcmd"
	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_json"
	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_obj"
	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_packet"
)

// bytes base demux fn map

var DemuxRsp2BytesFnMap = [...]func(me interface{}, hd w3d_packet.Header, rbody []byte) error{
	w3d_idcmd.Invalid:   bytesRecvRspFn_Invalid,   // Invalid not used, make empty packet error
	w3d_idcmd.Login:     bytesRecvRspFn_Login,     // Login make session with nickname and enter stage
	w3d_idcmd.Heartbeat: bytesRecvRspFn_Heartbeat, // Heartbeat prevent connection timeout
	w3d_idcmd.Chat:      bytesRecvRspFn_Chat,      // Chat chat to stage
	w3d_idcmd.Act:       bytesRecvRspFn_Act,       // Act send user action
	w3d_idcmd.StatsInfo: bytesRecvRspFn_StatsInfo, // StatsInfo game stats info

}

// Invalid not used, make empty packet error
func bytesRecvRspFn_Invalid(me interface{}, hd w3d_packet.Header, rbody []byte) error {
	robj, err := w3d_json.UnmarshalPacket(hd, rbody)
	if err != nil {
		return fmt.Errorf("Packet type miss match %v", rbody)
	}
	recved, ok := robj.(*w3d_obj.RspInvalid_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", robj)
	}
	return fmt.Errorf("Not implemented %v", recved)
}

// Login make session with nickname and enter stage
func bytesRecvRspFn_Login(me interface{}, hd w3d_packet.Header, rbody []byte) error {
	robj, err := w3d_json.UnmarshalPacket(hd, rbody)
	if err != nil {
		return fmt.Errorf("Packet type miss match %v", rbody)
	}
	recved, ok := robj.(*w3d_obj.RspLogin_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", robj)
	}
	return fmt.Errorf("Not implemented %v", recved)
}

// Heartbeat prevent connection timeout
func bytesRecvRspFn_Heartbeat(me interface{}, hd w3d_packet.Header, rbody []byte) error {
	robj, err := w3d_json.UnmarshalPacket(hd, rbody)
	if err != nil {
		return fmt.Errorf("Packet type miss match %v", rbody)
	}
	recved, ok := robj.(*w3d_obj.RspHeartbeat_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", robj)
	}
	return fmt.Errorf("Not implemented %v", recved)
}

// Chat chat to stage
func bytesRecvRspFn_Chat(me interface{}, hd w3d_packet.Header, rbody []byte) error {
	robj, err := w3d_json.UnmarshalPacket(hd, rbody)
	if err != nil {
		return fmt.Errorf("Packet type miss match %v", rbody)
	}
	recved, ok := robj.(*w3d_obj.RspChat_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", robj)
	}
	return fmt.Errorf("Not implemented %v", recved)
}

// Act send user action
func bytesRecvRspFn_Act(me interface{}, hd w3d_packet.Header, rbody []byte) error {
	robj, err := w3d_json.UnmarshalPacket(hd, rbody)
	if err != nil {
		return fmt.Errorf("Packet type miss match %v", rbody)
	}
	recved, ok := robj.(*w3d_obj.RspAct_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", robj)
	}
	return fmt.Errorf("Not implemented %v", recved)
}

// StatsInfo game stats info
func bytesRecvRspFn_StatsInfo(me interface{}, hd w3d_packet.Header, rbody []byte) error {
	robj, err := w3d_json.UnmarshalPacket(hd, rbody)
	if err != nil {
		return fmt.Errorf("Packet type miss match %v", rbody)
	}
	recved, ok := robj.(*w3d_obj.RspStatsInfo_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", robj)
	}
	return fmt.Errorf("Not implemented %v", recved)
}
