// Code generated by "genprotocol -ver=213afa194ef0e682076c6a0cbf801946c13d343cc54330be7c4557e46057a498 -basedir=. -prefix=w3d -statstype=int"

package w3d_handlersp

/* obj base demux fn map template

var DemuxRsp2ObjFnMap = [...]func(me interface{}, hd w3d_packet.Header, body interface{}) error {
w3d_idcmd.Invalid : objRecvRspFn_Invalid,
w3d_idcmd.EnterStage : objRecvRspFn_EnterStage,
w3d_idcmd.ChatToStage : objRecvRspFn_ChatToStage,
w3d_idcmd.Heartbeat : objRecvRspFn_Heartbeat,

}

	func objRecvRspFn_Invalid(me interface{}, hd w3d_packet.Header, body interface{}) error {
		robj , ok := body.(*w3d_obj.RspInvalid_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	func objRecvRspFn_EnterStage(me interface{}, hd w3d_packet.Header, body interface{}) error {
		robj , ok := body.(*w3d_obj.RspEnterStage_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	func objRecvRspFn_ChatToStage(me interface{}, hd w3d_packet.Header, body interface{}) error {
		robj , ok := body.(*w3d_obj.RspChatToStage_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	func objRecvRspFn_Heartbeat(me interface{}, hd w3d_packet.Header, body interface{}) error {
		robj , ok := body.(*w3d_obj.RspHeartbeat_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

*/
