// Code generated by "genenum -typename=GameObjType -packagename=gameobjtype -basedir=enum -statstype=int"

package gameobjtype_stats

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/gowasm3dgame/enum/gameobjtype"
)

type GameObjTypeStat [gameobjtype.GameObjType_Count]int

func (es *GameObjTypeStat) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "GameObjTypeStats[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			gameobjtype.GameObjType(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *GameObjTypeStat) Dec(e gameobjtype.GameObjType) {
	es[e] -= 1
}
func (es *GameObjTypeStat) Inc(e gameobjtype.GameObjType) {
	es[e] += 1
}
func (es *GameObjTypeStat) Add(e gameobjtype.GameObjType, v int) {
	es[e] += v
}
func (es *GameObjTypeStat) SetIfGt(e gameobjtype.GameObjType, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es *GameObjTypeStat) Get(e gameobjtype.GameObjType) int {
	return es[e]
}

func (es *GameObjTypeStat) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>GameObjType statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return gameobjtype.GameObjType(i).String()
}

var IndexFn = template.FuncMap{
	"GameObjTypeIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{GameObjTypeIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
