// Code generated by "genprotocol -ver=ac2fd1af64d4f1613e3d88467403507d7d0ff89c9b04f7811f8dd396f85bb42f -basedir=. -prefix=w3d -statstype=int"

package w3d_const

import "time"

const (
	// MaxBodyLen set to max body len, affect send/recv buffer size
	MaxBodyLen = 0xfffff
	// PacketBufferPoolSize max size of pool packet buffer
	PacketBufferPoolSize = 100

	// ServerAPICallTimeOutDur api call watchdog timer
	ServerAPICallTimeOutDur = time.Second * 2
)
