// Code generated by "genprotocol -ver=f5b1d289172cf84ad5d01b91533408be6b17961cf28ddd6fe767224298a8aedd -basedir=. -prefix=w3d -statstype=int"

package w3d_gob

import (
	"bytes"
	"encoding/gob"
	"fmt"

	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_idcmd"
	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_idnoti"
	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_obj"
	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_packet"
)

// marshal body and append to oldBufferToAppend
// and return newbuffer, body type, error
func MarshalBodyFn(body interface{}, oldBuffToAppend []byte) ([]byte, byte, error) {
	network := bytes.NewBuffer(oldBuffToAppend)
	enc := gob.NewEncoder(network)
	err := enc.Encode(body)
	return network.Bytes(), 0, err
}

func UnmarshalPacket(h w3d_packet.Header, bodyData []byte) (interface{}, error) {
	switch h.FlowType {
	case w3d_packet.Request:
		if int(h.Cmd) >= len(ReqUnmarshalMap) {
			return nil, fmt.Errorf("unknown request command: %v %v",
				h.FlowType, w3d_idcmd.CommandID(h.Cmd))
		}
		return ReqUnmarshalMap[h.Cmd](h, bodyData)

	case w3d_packet.Response:
		if int(h.Cmd) >= len(RspUnmarshalMap) {
			return nil, fmt.Errorf("unknown response command: %v %v",
				h.FlowType, w3d_idcmd.CommandID(h.Cmd))
		}
		return RspUnmarshalMap[h.Cmd](h, bodyData)

	case w3d_packet.Notification:
		if int(h.Cmd) >= len(NotiUnmarshalMap) {
			return nil, fmt.Errorf("unknown notification command: %v %v",
				h.FlowType, w3d_idcmd.CommandID(h.Cmd))
		}
		return NotiUnmarshalMap[h.Cmd](h, bodyData)
	}
	return nil, fmt.Errorf("unknown packet FlowType %v", h.FlowType)
}

var ReqUnmarshalMap = [...]func(h w3d_packet.Header, bodyData []byte) (interface{}, error){
	w3d_idcmd.Invalid:   unmarshal_ReqInvalid,
	w3d_idcmd.MakeTeam:  unmarshal_ReqMakeTeam,
	w3d_idcmd.Act:       unmarshal_ReqAct,
	w3d_idcmd.Heartbeat: unmarshal_ReqHeartbeat,
}

var RspUnmarshalMap = [...]func(h w3d_packet.Header, bodyData []byte) (interface{}, error){
	w3d_idcmd.Invalid:   unmarshal_RspInvalid,
	w3d_idcmd.MakeTeam:  unmarshal_RspMakeTeam,
	w3d_idcmd.Act:       unmarshal_RspAct,
	w3d_idcmd.Heartbeat: unmarshal_RspHeartbeat,
}

var NotiUnmarshalMap = [...]func(h w3d_packet.Header, bodyData []byte) (interface{}, error){
	w3d_idnoti.Invalid:   unmarshal_NotiInvalid,
	w3d_idnoti.StageInfo: unmarshal_NotiStageInfo,
	w3d_idnoti.StatsInfo: unmarshal_NotiStatsInfo,
}

func unmarshal_ReqInvalid(h w3d_packet.Header, bodyData []byte) (interface{}, error) {
	var args w3d_obj.ReqInvalid_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func unmarshal_RspInvalid(h w3d_packet.Header, bodyData []byte) (interface{}, error) {
	var args w3d_obj.RspInvalid_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func unmarshal_ReqMakeTeam(h w3d_packet.Header, bodyData []byte) (interface{}, error) {
	var args w3d_obj.ReqMakeTeam_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func unmarshal_RspMakeTeam(h w3d_packet.Header, bodyData []byte) (interface{}, error) {
	var args w3d_obj.RspMakeTeam_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func unmarshal_ReqAct(h w3d_packet.Header, bodyData []byte) (interface{}, error) {
	var args w3d_obj.ReqAct_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func unmarshal_RspAct(h w3d_packet.Header, bodyData []byte) (interface{}, error) {
	var args w3d_obj.RspAct_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func unmarshal_ReqHeartbeat(h w3d_packet.Header, bodyData []byte) (interface{}, error) {
	var args w3d_obj.ReqHeartbeat_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func unmarshal_RspHeartbeat(h w3d_packet.Header, bodyData []byte) (interface{}, error) {
	var args w3d_obj.RspHeartbeat_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func unmarshal_NotiInvalid(h w3d_packet.Header, bodyData []byte) (interface{}, error) {
	var args w3d_obj.NotiInvalid_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func unmarshal_NotiStageInfo(h w3d_packet.Header, bodyData []byte) (interface{}, error) {
	var args w3d_obj.NotiStageInfo_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func unmarshal_NotiStatsInfo(h w3d_packet.Header, bodyData []byte) (interface{}, error) {
	var args w3d_obj.NotiStatsInfo_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}
