// Code generated by "genenum -typename=GameObjType -packagename=gameobjtype -basedir=enums -statstype=int"

package gameobjtype

import "fmt"

type GameObjType uint8

const (
	Nil           GameObjType = iota //
	Ball                             //
	Shield                           //
	Bullet                           //
	HommingBullet                    //
	SuperBullet                      //
	Deco                             //
	Mark                             //
	Hard                             //
	Food                             //

	GameObjType_Count int = iota
)

var _GameObjType2string = [GameObjType_Count]string{
	Nil:           "Nil",
	Ball:          "Ball",
	Shield:        "Shield",
	Bullet:        "Bullet",
	HommingBullet: "HommingBullet",
	SuperBullet:   "SuperBullet",
	Deco:          "Deco",
	Mark:          "Mark",
	Hard:          "Hard",
	Food:          "Food",
}

func (e GameObjType) String() string {
	if e >= 0 && e < GameObjType(GameObjType_Count) {
		return _GameObjType2string[e]
	}
	return fmt.Sprintf("GameObjType%d", uint8(e))
}

var _string2GameObjType = map[string]GameObjType{
	"Nil":           Nil,
	"Ball":          Ball,
	"Shield":        Shield,
	"Bullet":        Bullet,
	"HommingBullet": HommingBullet,
	"SuperBullet":   SuperBullet,
	"Deco":          Deco,
	"Mark":          Mark,
	"Hard":          Hard,
	"Food":          Food,
}

func String2GameObjType(s string) (GameObjType, bool) {
	v, b := _string2GameObjType[s]
	return v, b
}
