// Code generated by "genprotocol -ver=213afa194ef0e682076c6a0cbf801946c13d343cc54330be7c4557e46057a498 -basedir=. -prefix=w3d -statstype=int"

package w3d_handlereq

/* obj base demux fn map template
	var DemuxReq2ObjAPIFnMap = [...]func(
		me interface{}, hd w3d_packet.Header, robj interface{}) (
		w3d_packet.Header, interface{}, error){
	w3d_idcmd.Invalid: Req2ObjAPI_Invalid,
w3d_idcmd.EnterStage: Req2ObjAPI_EnterStage,
w3d_idcmd.ChatToStage: Req2ObjAPI_ChatToStage,
w3d_idcmd.Heartbeat: Req2ObjAPI_Heartbeat,

}   // DemuxReq2ObjAPIFnMap

	func Req2ObjAPI_Invalid(
		me interface{}, hd w3d_packet.Header, robj interface{}) (
		w3d_packet.Header, interface{},  error) {
		req, ok := robj.(*w3d_obj.ReqInvalid_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqInvalid(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqInvalid(
		me interface{}, hd w3d_packet.Header, robj *w3d_obj.ReqInvalid_data) (
		w3d_packet.Header, *w3d_obj.RspInvalid_data, error) {
		sendHeader := w3d_packet.Header{
			ErrorCode : w3d_error.None,
		}
		sendBody := &w3d_obj.RspInvalid_data{
		}
		return sendHeader, sendBody, nil
	}

	func Req2ObjAPI_EnterStage(
		me interface{}, hd w3d_packet.Header, robj interface{}) (
		w3d_packet.Header, interface{},  error) {
		req, ok := robj.(*w3d_obj.ReqEnterStage_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqEnterStage(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqEnterStage(
		me interface{}, hd w3d_packet.Header, robj *w3d_obj.ReqEnterStage_data) (
		w3d_packet.Header, *w3d_obj.RspEnterStage_data, error) {
		sendHeader := w3d_packet.Header{
			ErrorCode : w3d_error.None,
		}
		sendBody := &w3d_obj.RspEnterStage_data{
		}
		return sendHeader, sendBody, nil
	}

	func Req2ObjAPI_ChatToStage(
		me interface{}, hd w3d_packet.Header, robj interface{}) (
		w3d_packet.Header, interface{},  error) {
		req, ok := robj.(*w3d_obj.ReqChatToStage_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqChatToStage(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqChatToStage(
		me interface{}, hd w3d_packet.Header, robj *w3d_obj.ReqChatToStage_data) (
		w3d_packet.Header, *w3d_obj.RspChatToStage_data, error) {
		sendHeader := w3d_packet.Header{
			ErrorCode : w3d_error.None,
		}
		sendBody := &w3d_obj.RspChatToStage_data{
		}
		return sendHeader, sendBody, nil
	}

	func Req2ObjAPI_Heartbeat(
		me interface{}, hd w3d_packet.Header, robj interface{}) (
		w3d_packet.Header, interface{},  error) {
		req, ok := robj.(*w3d_obj.ReqHeartbeat_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqHeartbeat(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqHeartbeat(
		me interface{}, hd w3d_packet.Header, robj *w3d_obj.ReqHeartbeat_data) (
		w3d_packet.Header, *w3d_obj.RspHeartbeat_data, error) {
		sendHeader := w3d_packet.Header{
			ErrorCode : w3d_error.None,
		}
		sendBody := &w3d_obj.RspHeartbeat_data{
		}
		return sendHeader, sendBody, nil
	}

*/
