// Code generated by "genprotocol -ver=fd815e2fbc449528b4fb5d55480af0a03b4bfaf074ff2c5570d2e5a3ce03896b -basedir=. -prefix=w3d -statstype=int"

package w3d_handlereq

/* obj base demux fn map template
	var DemuxReq2ObjAPIFnMap = [...]func(
		me interface{}, hd w3d_packet.Header, robj interface{}) (
		w3d_packet.Header, interface{}, error){
	w3d_idcmd.Invalid: Req2ObjAPI_Invalid,
w3d_idcmd.Login: Req2ObjAPI_Login,
w3d_idcmd.Heartbeat: Req2ObjAPI_Heartbeat,
w3d_idcmd.Chat: Req2ObjAPI_Chat,
w3d_idcmd.EnterStage: Req2ObjAPI_EnterStage,

}   // DemuxReq2ObjAPIFnMap

	func Req2ObjAPI_Invalid(
		me interface{}, hd w3d_packet.Header, robj interface{}) (
		w3d_packet.Header, interface{},  error) {
		req, ok := robj.(*w3d_obj.ReqInvalid_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqInvalid(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqInvalid(
		me interface{}, hd w3d_packet.Header, robj *w3d_obj.ReqInvalid_data) (
		w3d_packet.Header, *w3d_obj.RspInvalid_data, error) {
		sendHeader := w3d_packet.Header{
			ErrorCode : w3d_error.None,
		}
		sendBody := &w3d_obj.RspInvalid_data{
		}
		return sendHeader, sendBody, nil
	}

	func Req2ObjAPI_Login(
		me interface{}, hd w3d_packet.Header, robj interface{}) (
		w3d_packet.Header, interface{},  error) {
		req, ok := robj.(*w3d_obj.ReqLogin_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqLogin(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqLogin(
		me interface{}, hd w3d_packet.Header, robj *w3d_obj.ReqLogin_data) (
		w3d_packet.Header, *w3d_obj.RspLogin_data, error) {
		sendHeader := w3d_packet.Header{
			ErrorCode : w3d_error.None,
		}
		sendBody := &w3d_obj.RspLogin_data{
		}
		return sendHeader, sendBody, nil
	}

	func Req2ObjAPI_Heartbeat(
		me interface{}, hd w3d_packet.Header, robj interface{}) (
		w3d_packet.Header, interface{},  error) {
		req, ok := robj.(*w3d_obj.ReqHeartbeat_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqHeartbeat(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqHeartbeat(
		me interface{}, hd w3d_packet.Header, robj *w3d_obj.ReqHeartbeat_data) (
		w3d_packet.Header, *w3d_obj.RspHeartbeat_data, error) {
		sendHeader := w3d_packet.Header{
			ErrorCode : w3d_error.None,
		}
		sendBody := &w3d_obj.RspHeartbeat_data{
		}
		return sendHeader, sendBody, nil
	}

	func Req2ObjAPI_Chat(
		me interface{}, hd w3d_packet.Header, robj interface{}) (
		w3d_packet.Header, interface{},  error) {
		req, ok := robj.(*w3d_obj.ReqChat_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqChat(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqChat(
		me interface{}, hd w3d_packet.Header, robj *w3d_obj.ReqChat_data) (
		w3d_packet.Header, *w3d_obj.RspChat_data, error) {
		sendHeader := w3d_packet.Header{
			ErrorCode : w3d_error.None,
		}
		sendBody := &w3d_obj.RspChat_data{
		}
		return sendHeader, sendBody, nil
	}

	func Req2ObjAPI_EnterStage(
		me interface{}, hd w3d_packet.Header, robj interface{}) (
		w3d_packet.Header, interface{},  error) {
		req, ok := robj.(*w3d_obj.ReqEnterStage_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqEnterStage(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqEnterStage(
		me interface{}, hd w3d_packet.Header, robj *w3d_obj.ReqEnterStage_data) (
		w3d_packet.Header, *w3d_obj.RspEnterStage_data, error) {
		sendHeader := w3d_packet.Header{
			ErrorCode : w3d_error.None,
		}
		sendBody := &w3d_obj.RspEnterStage_data{
		}
		return sendHeader, sendBody, nil
	}

*/
