// Code generated by "genenum.exe -typename=ActType -packagename=acttype -basedir=enum -vectortype=int"

package acttype_vector

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/gowasm3dgame/enum/acttype"
)

type ActTypeVector [acttype.ActType_Count]int

func (es ActTypeVector) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "ActTypeVector[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			acttype.ActType(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *ActTypeVector) Dec(e acttype.ActType) {
	es[e] -= 1
}
func (es *ActTypeVector) Inc(e acttype.ActType) {
	es[e] += 1
}
func (es *ActTypeVector) Add(e acttype.ActType, v int) {
	es[e] += v
}
func (es *ActTypeVector) SetIfGt(e acttype.ActType, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es ActTypeVector) Get(e acttype.ActType) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es ActTypeVector) Iter(fn func(i acttype.ActType, v int) bool) bool {
	for i, v := range es {
		if fn(acttype.ActType(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es ActTypeVector) VectorAdd(arg ActTypeVector) ActTypeVector {
	var rtn ActTypeVector
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es ActTypeVector) VectorSub(arg ActTypeVector) ActTypeVector {
	var rtn ActTypeVector
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *ActTypeVector) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>ActType statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return acttype.ActType(i).String()
}

var IndexFn = template.FuncMap{
	"ActTypeIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{ActTypeIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
