// Code generated by "genprotocol -ver=213afa194ef0e682076c6a0cbf801946c13d343cc54330be7c4557e46057a498 -basedir=. -prefix=w3d -statstype=int"

package w3d_error_stats

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_error"
)

type ErrorCodeStat [w3d_error.ErrorCode_Count]int

func (es *ErrorCodeStat) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "ErrorCodeStats[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			w3d_error.ErrorCode(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *ErrorCodeStat) Inc(e w3d_error.ErrorCode) {
	es[e] += 1
}
func (es *ErrorCodeStat) Add(e w3d_error.ErrorCode, v int) {
	es[e] += v
}
func (es *ErrorCodeStat) SetIfGt(e w3d_error.ErrorCode, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es *ErrorCodeStat) Get(e w3d_error.ErrorCode) int {
	return es[e]
}

func (es *ErrorCodeStat) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>ErrorCode statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return w3d_error.ErrorCode(i).String()
}

var IndexFn = template.FuncMap{
	"ErrorCodeIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{ErrorCodeIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
