// Code generated by "genprotocol -ver=de39b3963afaad4ed2557809c9208a5676bf9321c0823e0dac15bc4db6d51552 -basedir=. -prefix=w3d -statstype=int"

package w3d_statapierror

import (
	"fmt"
	"html/template"
	"net/http"
	"sync"

	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_error"
	"github.com/kasworld/gowasm3dgame/protocol_w3d/w3d_idcmd"
)

func (es *StatAPIError) String() string {
	return fmt.Sprintf(
		"StatAPIError[%v %v %v]",
		len(es.Stat),
		len(es.ECList),
		len(es.CmdList),
	)
}

type StatAPIError struct {
	mutex   sync.RWMutex
	Stat    [][]int
	ECList  []string
	CmdList []string
}

func New() *StatAPIError {
	es := &StatAPIError{
		Stat: make([][]int, w3d_idcmd.CommandID_Count),
	}
	for i, _ := range es.Stat {
		es.Stat[i] = make([]int, w3d_error.ErrorCode_Count)
	}
	es.ECList = make([]string, w3d_error.ErrorCode_Count)
	for i, _ := range es.ECList {
		es.ECList[i] = fmt.Sprintf("%s", w3d_error.ErrorCode(i).String())
	}
	es.CmdList = make([]string, w3d_idcmd.CommandID_Count)
	for i, _ := range es.CmdList {
		es.CmdList[i] = fmt.Sprintf("%v", w3d_idcmd.CommandID(i))
	}
	return es
}
func (es *StatAPIError) Inc(cmd w3d_idcmd.CommandID, errorcode w3d_error.ErrorCode) {
	es.mutex.Lock()
	defer es.mutex.Unlock()
	es.Stat[cmd][errorcode]++
}
func (es *StatAPIError) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Parse(`
	<html><head><title>API Error stat Info</title></head><body>
	<table border=1 style="border-collapse:collapse;">
	<tr>
		<td></td>
		{{range $ft, $v := .ECList}}
			<th>{{$v}}</th>
		{{end}}
	</tr>
	{{range $cmd, $w := .Stat}}
		<tr>
			<td>{{index $.CmdList $cmd}}</td>
			{{range $ft, $v := $w}}
				<td>{{$v}}</td>
			{{end}}
		</tr>
	{{end}}
	<tr>
		<td></td>
		{{range $ft, $v := .ECList}}
			<th>{{$v}}</th>
		{{end}}
	</tr>
	</table><br/>
	</body></html>`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}
